
# SwiftLintFramework Docs: https://realm.github.io/SwiftLint/index.html
# ルール追加時の参考: https://qiita.com/uhooi/items/7f5d6cf2b240f60ba1ed

# 無効にするルール
disabled_rules:
  - orphaned_doc_comment
  - type_body_length
  - switch_case_alignment
  - trailing_comma
  - identifier_name
  - file_length
  - function_body_length
  - type_name
  - inclusive_language
#  App Delegateにも影響するため、追加した
  - force_cast
  - multiple_closures_with_trailing_closure
  - unused_optional_binding

# 有効にするルール
opt_in_rules:

######### 以下プロジェクトにより適宜変更する ######

# 対象のファイル・フォルダ
included:

# 対象外のファイル・フォルダ
excluded:
  - Pods

########################################

#一行の行数
line_length: 200
#  error: 200　errorつけない方が良い？

cyclomatic_complexity:
  warning: 25
